## Tributo
ENERGIA_ACCION_HEROICA = 30
POPULARIDAD_ACCION_HEROICA = 3
ENERGIA_BOLITA = 20

## Tributo / Objeto
COSTO_OBJETO = 2
AUMENTAR_ENERGIA = 20
PONDERADOR_AUMENTAR_FUERZA = 2
AUMENTAR_AGILIDAD = 3
AUMENTAR_INGENIO = 3

##Ambiente (playa)
VELOCIDAD_VIENTOS_PLAYA = 100
HUMEDAD_PLAYA = 100

## Ambiente (Montaña)
NUBOSIDAD_MONTAÑA = 100
PRECIPITACIONES_MONTAÑA = 100

## Ambiente (Bosque)
PRECIPITACIONES_BOSQUE = 100
VELOCIDAD_VIENTOS_BOSQUE = 100

## Arenas
PROBABILIDAD_EVENTO = 3.33

